[package]
name = "rpi-mesh-plugin-manager"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs_extra = "1.2.0"
reqwest = { version = "0.11.12", features = ["blocking"] }